#! /bin/bash

function explain_pkg {
    printf "  $1\t\t$2\n"
}

function show_usage {
    printf "Usage: $0 <package>\n\n"
    explain_pkg "deps" "install dependencies - this should be run first"
    explain_pkg "vim" "build and install vim 7.3 from source"
}

if [ -z $1 ]
then
    show_usage
    exit 1
fi

if [[ $1 != "deps" && ! -f /var/cache/DEPS_INSTALLED ]]
then
    echo "You need to run the following command before performing any further operation:"
    printf "\t$0 deps\n"
    exit 1
fi

export NUM_OF_CORES=`cat /proc/cpuinfo | grep processor | wc -l`
$1/setup.sh
